using System.Diagnostics;
using MineCLI.Utils;

namespace MineCLI.Server
{
    public class Server
    {

        public readonly ServerSoftware Software;
        public readonly string Version;

        public Server(ServerSoftware software, string version)
        {
            this.Software = software;
            this.Version = version;
        }

        public string GetJarFileName()
        {
            return this.Software.Name + "-" + this.Version + ".jar";
        }

        public string GetArtifactURL()
        {
            return this.Software.GetArtifact(this.Version);
        }

        public void Download()
        {
            string artifact = this.GetArtifactURL();
            HTTPUtils.DownloadFile(artifact, this.GetJarFileName());
        }

        public void PrepareEnvironment(string host, int port, bool onlineMode, string motd, int networkCompression, int maxPlayers)
        {
            // Accept eula
            if (this.Software.Type == "java-server")
            {
                FileUtils.CreateFile("eula.txt", "eula=true");

                string appendContent = "#Minecraft server properties\n#Self generated by MineCLI";

                appendContent += "server-ip=" + host + "\n";
                appendContent += "server-port=" + port + "\n";
                appendContent += "online-mode=" + onlineMode.ToString().ToLower() + "\n";
                appendContent += "motd=" + motd + "\n";
                appendContent += "network-compression-threshold=" + networkCompression + "\n";
                appendContent += "max-players=" + maxPlayers;

                FileUtils.CreateFileIfNotExist("server.properties", appendContent);
            }
        }

        public void Run()
        {
            Process proc = new Process();
            proc.StartInfo.FileName = "java";
            proc.StartInfo.Arguments = "-jar " + this.GetJarFileName();
            proc.Start();
            proc.WaitForExit();
        }
    }
}